#! /bin/sh
### BEGIN INIT INFO
# Provides:          zombieland
# Required-Start:    docker
# Required-Stop:     docker
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Brains!!
# Description:       Enable service provided by zombieland.
### END INIT INFO
#
# Author: Leandro Duque Mussio <l.mussio@outlook.com>

#
# Function that starts the daemon/service
#
do_start()
{
	start docker
	count=$(docker ps -a | grep " zombieland " | wc -l)
	if [ "$count" -eq 0 ]; then
		docker run --name zombieland -d lmussio/cc4211
	else
		docker start zombieland
	fi
}

#
# Function that stops the daemon/service
#
do_stop()
{
	docker stop zombieland
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  status)
	docker ps -a --filter="name=zombieland" | grep "NAMES\| zombieland "
	;;
  restart|force-reload)
	do_stop
	do_start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac
